version: 2
jobs:
  build:
    working_directory: ~/JavaScriptApiAutomation
    docker:
      - image: circleci/node:8.0
      - image: mongo:3.4.4
    steps:
      - run:
          name: "Checking NodeJs + NPM Version"
          command: |
            node --version
            npm --version
      - checkout
      # - run:
      #     name: Update-npm
      #     command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      # - run:
      #     name: Install-npm-wee
      #     command: 'sudo npm install'
      - run:
          name: Install-Mocha
          command: 'sudo npm i -g mocha'
      - run:
          name: Run-Tests
          command: 'npm test'
      - run:
          name: Code-Coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml